### ISSUE TITLE
EntityDescriptorProvider for IdP

### ISSUE THREAD

**Issue by ntoniazzi** [lightSAML/SpBundle#14]
Hi,
I'm trying to move some projects from AerialShip SamlSpBundle to lightSaml SpBundle and I'm facing some issues.
For an application acting as an SP, I was using an entity descriptor provider for the IdP declaration. But the new symfony bridge configuration seems to only allow static xml files.
Is there a way to configure a service implementing the EntityDescriptorProviderInterface somewhere?

**Comment by tmilos** [comment]
@ntoniazzi Sure, but now it's renamed to [``EntityDescriptorStoreInterface``](https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Store/EntityDescriptor/EntityDescriptorStoreInterface.php). You can define a service that implements that ``EntityDescriptorStoreInterface`` and tag it with [``lightsaml.idp_entity_store``](http://www.lightsaml.com/Symfony-Bridge/Configuration/) tag - so you can "dynamically" provide what ever IDP metadata you want. It will also automatically extract certificate credentials out of it, so there's no need to do any additional ``lightsaml.credential`` tagging. Hope this answers your question and I understood it well.

**Comment by ntoniazzi** [comment]
That's exactly what I was looking for.

Thanks.
