### ISSUE TITLE
Error while downloading via composer

### ISSUE THREAD

**Issue by INSEAD-asim** [lightSAML/SpBundle#17]
Hi,

I am facing issue while downloading package via composer. I am using command `composer require "lightsaml/sp-bundle"` but it is showing following error. Appreciate help on this.

> 
> [InvalidArgumentException]
> Could not find package lightsaml/sp-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by INSEAD-asim** [comment]
Hi,

I able to resolve issue. It was due to `platform` settings in `composer.json` which forces to use `php 5.3.9`. I removed this setting and package downloaded fine.

**Comment by tmilos** [comment]
@INSEAD-asim guess you created your project with the symfony cli, right? I had such issue with ``platform`` myself on some other project.

**Comment by INSEAD-asim** [comment]
Yes @tmilos! You are right. I created project with symfony cli. But it was good learning for me when I solved this issue.
