### ISSUE TITLE
The OpenIdP has been shut down

### ISSUE THREAD

**Issue by maslakoff** [lightSAML/SpBundle#24]
Hello,

The OpenIdP has been shut down. It is no longer possible to use it to test your SAML Service Provider. If you were using it for that purpose, you will need to look for alternatives.

Do you know any possible solution to test the saml SP?

**Comment by dameert** [comment]
The OpenIdp seems to be accessible to me (it appears as an option on the http://localhost:8000/saml/discovery page). When I click it (https://openidp.feide.no) I can create a new account.

**Comment by tmilos** [comment]
You can check [lightSAML/DemoSP](https://github.com/lightSAML/DemoSP) as an example. It uses [lightSAML/SpBundle](https://github.com/lightSAML/SpBundle) and integrates with 3 IDPs: openidp, testshib and [lightSAML/lightSAML-IDP](https://github.com/lightSAML/lightSAML-IDP) at localhost.

Though [OpenIDP](https://openidp.feide.no/) works, it says it's "restricted to UNINETT", and I'm unable anymore to find my SP registration info... so it seems out. 

[TestShib](http://www.testshib.org/) worked last time I tried. Guess you can still use it for testing... Though, sometimes I had to reregisted as SP, seems registrations expire.

If nothing, you could try with [lightSAML/lightSAML-IDP](https://github.com/lightSAML/lightSAML-IDP) which is not quite polished and documented, but will work if you sniff a bit around [IDP config](https://github.com/lightSAML/lightSAML-IDP/blob/master/web/idp/_config.php)

I don't know any other open/free IDP you could use for testing. And I had no need for it, these few, plus local ADFS and remote Azure were enough... But if anybody knows any... please post it and share with others.

**Comment by Ronnie-J** [comment]
Another option to [lightSAML/lightSAML-IDP](https://github.com/lightSAML/lightSAML-IDP) is [SimpleSamlPHP](https://simplesamlphp.org/). I've used it a couple of times as a dummy identity provider. It's a bigger project because of its ability to be SP and IDP (and have a lot of modules) but pretty easy to set up if your confutable with SAML terminology.
