### ISSUE TITLE
simple saml path

### ISSUE THREAD

**Issue by licarigianluca** [lightSAML/SpBundle#28]
hi,
i have a legacy application that works with simplesamlphp but i'm trying to make it work inside symfony framework. I looked at the documentation but i didn't find a section in which is described well the location of the simplesamlphp config directory.
For example in my application i use simplesaml/configuration.php for telling to the app who is the IDP. 
Where I have to put these  files inside the symfony framework directories?

THX

**Comment by tmilos** [comment]
@licarigianluca this is not a simplesamlphp app. LightSAML library is an alternate independant implentation of SAML 2.0 protocol in PHP, and provides a symfony bundle. So, I could help you only with LightSAML and not with simplesamlphp.
