### ISSUE TITLE
Adding checkPreAuth before authenticating

### ISSUE THREAD

**Issue by rudott** [lightSAML/SpBundle#31]
@tmilos In the old repository there was a PR for adding the checkPreAuth, is it possible to add this feature, because I think it would be necessary for extra security checks.
https://github.com/aerialship/SamlSPBundle/pull/44/files

By adding this check it's possible to add the default checks isAccountNonLocked, isEnabled & isAccountNonExpired by using the AdvancedUserInterface.

Should I create a PR for this (including the missing test)? 

Thank you!

**Comment by tmilos** [comment]
Yes please make the PR. I guess it should be placed right above existing ``checkPostAuth`` call since authentication actually is not really done internally by the system, but relays on the received assertions.

**Comment by rudott** [comment]
@tmilos thanks for your quick reply. I created the PR: https://github.com/lightSAML/SpBundle/pull/32

**Comment by tmilos** [comment]
Merged and released in [v1.0.3](https://github.com/lightSAML/SpBundle/releases/tag/1.0.3)
Thanks
