### ISSUE TITLE
Configuration of the bundle

### ISSUE THREAD

**Issue by gpeanodc** [lightSAML/SpBundle#43]
Hi,

Thanks for your bundle. I'm new in using SAML protocol and I don't understand how can I get the site metadata for IDP implementation ?

I'm not really understand what I should write in this config parameter(entity_id) ? The url of my website ?

entity_id: http://localhost/lightsaml/demosp

Can you help me ?

I don't know if it's the right place for making questions, sorry if not.

**Comment by tmilos** [comment]
It's your ID, url of your website will work

**Comment by gpeanodc** [comment]
Thank you very much.

There was another question in my issue : how Can I get( or build) metadata of my app to give them to IDP ?

Thank you.

**Comment by gpeanodc** [comment]
I did not see that we have a /metadata.xml route. I'll see that tomorrow. Thanks.

**Comment by majost-colombia** [comment]
Hi, I'm an very strange issue, when I try access to http://mydomain.com/lightsaml/demosp I get an "404 Route not found", I already import the routing file from the bundle and cleared the cache. The /lightsaml/login_check route neither work
