### ISSUE TITLE
didn't create roles for SamlSpToken

### ISSUE THREAD

**Issue by wax13003** [lightSAML/SpBundle#57]
came with an error below:

Catchable Fatal Error: Argument 1 passed to LightSaml\SpBundle\Security\Authentication\Token\SamlSpToken::__construct() must be of the type array, null given,

When I checked the token created in SamlSpTokenFactory, didn't create the roles while that could not be null in SamlSpToken->__construct. Could anyone help me with this?

in vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Security/Authentication/Token/SamlSpToken.php (line 27)
SamlSpToken->__construct(null, 'main', array('username' => 'johndoe', 'email' => 'john@doe.com'), object(User))
in vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Security/Authentication/Token/SamlSpTokenFactory.php (line 34)
        $token = new SamlSpToken(            $user instanceof UserInterface ? $user->getRoles() : [],            $providerKey,            $attributes,            $user        );        return $token;    }}
SamlSpTokenFactory->create('main', array('username' => 'johndoe', 'email' => 'john@doe.com'), object(User), object(SamlSpResponseToken))
in vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Security/Authentication/Provider/LightsSamlSpAuthenticationProvider.php (line 137)
            $result = $this->tokenFactory->create(                $this->providerKey,                $attributes,                $user,                $token            );        } else {            $result = new SamlSpToken(                $user instanceof UserInterface ? $user->getRoles() : [],                $this->providerKey,                $attributes,

**Comment by tmilos** [comment]
Seems like your user getRoles is returning null and by UserInterface it should return array

**Comment by wax13003** [comment]
Thanks, I have checked my User Entity, it has getRoles, and my user table has the roles field. May I know how to check the error with null given by getRoles? Thanks, I am following the steps by https://www.lightsaml.com/SP-Bundle/Getting-started/ 

/**
 * @ORM\Entity()
 */
class User implements UserInterface, \Serializable
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $username;

    /**
     * @var array
     * @ORM\Column(type="json_array")
     */
    protected $roles;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return array
     */
    public function getRoles()
    {
        return $this->roles;
    }

**Comment by wax13003** [comment]
solved

**Comment by tmilos** [comment]
How? What was the problem?
