### ISSUE TITLE
Error installing SPBundle on Symfony 4.0.9

### ISSUE THREAD

**Issue by jhonnynho** [lightSAML/SpBundle#77]
Hi, I have an error when I install this bundle, when I run this `$ composer.phar require lightsaml/sp-bundle`, then appears this error

`The child node "own" at path "light_saml_symfony_bridge" must be configured.`

What can I do?

Thanks in advance

**Comment by arturslogins** [comment]
Hey, what did you do to fix this issue?

**Comment by jhonnynho** [comment]
Hey @arturslogins, after installing the library you have to create the `light_saml_symfony_bridge.yaml` into the `config/packages` directory. That message is really a warning, when you run `$ composer.phar require lightsaml/sp-bundle` the bundle its installed. So, create the file and you have to put something like this.

```
light_saml_symfony_bridge:
    own:
        entity_id: http://localhost:8008/saml
        credentials:
            -
                certificate: "%kernel.root_dir%/../vendor/lightsaml/lightsaml/web/sp/saml.crt"
                key:         "%kernel.root_dir%/../vendor/lightsaml/lightsaml/web/sp/saml.key"
                password:    ~
    party:
        idp:
            files:
                - "%kernel.root_dir%/../src/Idp/idp.local.xml"
#                - "%kernel.root_dir%/../vendor/lightsaml/lightsaml/web/sp/openidp.feide.no.xml"
    store:
        id_state: id_store
```

I hope it helps you. See u.
