### ISSUE TITLE
SAML alongside traditional form login

### ISSUE THREAD

**Issue by iainmckay** [lightSAML/SpBundle#9]
I'm having problems providing both a SAML based login and a traditional login form. The SpBundle keeps redirecting to the IdP. Can you suggest a way to have both of these working together?

Regards,

**Comment by iainmckay** [comment]
I figured it out, it was a problem in my security.access_control :)

**Comment by Warxcell** [comment]
Please post your solution. I have same problem :)

**Comment by iainmckay** [comment]
I don't remember exactly what we did, what with it being 2 years ago :P

This was the state of our for the SAML related records in our `security.access_control` section around that time.

```
access_control:
- { path: ^/saml/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
- { path: ^/(login|login_check)$, roles: [IS_AUTHENTICATED_ANONYMOUSLY, IS_AUTHENTICATED_FULLY] }
- { path: ^/$, roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_ANONYMOUSLY] }
```

If I remember correctly we had this mis-configured and was causing the issue.

**Comment by Warxcell** [comment]
I see. Seems that I have other problem. I have traditional form login and SAML, but when I open restricted page, symfony redirects me to SAML Login, not traditional form.
